### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by jav3** [SlavOK400/Toronto-housing-price-prediction#1]
Hi,

You mentioned on your main page that "In order to avoid any confidentiality issues I have decided to recreate the project and use the similar techniques I used there but with the publicly available data. I took advantage of the Canadian government’s enforcement towards real estate companies to disclose their housing sales to the public.". 

You also noted a "Handcrafted housing dataset (time horizon - 1 year)". May I ask how you went about creating this dataset? e.g. was it via web scraping, contacting various real estate companies, or otherwise?

Thank you!

**Comment by slavaspirin** [comment]
Hello there,

I scrapped the data from https://www.zoocasa.com 
Highly recommending this website as it has lots of data to work with! The only problem is that it takes time to go through all the properties page by page.

Hope it helps.

Regards,
Slava

**Comment by jav3** [comment]
Thank you very much 👍
